### ISSUE TITLE
Add a Link header utility

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/camel-ldp#1]
This will be a convenience utility to process Link headers

**Comment by ajs6f** [comment]
Does this mean a kind of dispatch mechanism? E.g. upon detecting a header, check a registry and hand a context to a handler found in that registry?

**Comment by acoburn** [comment]
I was thinking about something much more basic. For instance, the use case that comes to mind is: filter all messages that have a `Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel="type"` header. There is enough variability in the format of link headers (optional spaces after the semicolon, optional quotes around parameters), that it seems silly to reimplement all of that in each camel route. Jax-RS has a nice [Link class](http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Link.html), but I definitely don't want to depend on all of Jax-RS just to use that class.

**Comment by ajs6f** [comment]
Oh, we're just talking about syntax convenience? Cool, cool.

**Comment by acoburn** [comment]
Exactly -- my basic design goal here is to leave all of the heavy lifting to existing camel components: e.g. `camel-http4`, `camel-jackson`, etc. The code in this repo would just be small convenience features that would be used in tandem with the standard components. I am _definitely not_ implementing another component when `camel-http4` does 99% of what I'll need.

In effect, the code here will address "all of those little things LDP adds on top of typical HTTP interactions" without getting into the business of writing our own HTTP client.

**Comment by ajs6f** [comment]
no_new_client++

**Comment by acoburn** [comment]
Resolved with https://github.com/trellis-ldp/camel-ldp/commit/b415f9142b2fb96469080842b2434deb3e70df66
